## Experiment 6

Code to import Pandas and NumPy library.

In [2]:
import pandas as pd
import numpy as np

Program to print first 20 rows.

In [3]:
df = pd.read_csv('AmesHousing.csv')
df.head(20)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.0,4920,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.0,5005,Pave,NaN,IR1,HLS,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.0,5389,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,189000
10,11,527163010,60,RL,75.0,10000,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,175900
11,12,527165230,20,RL,NaN,7980,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,Shed,500,3,2010,WD,Normal,185000
12,13,527166040,60,RL,63.0,8402,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,180400
13,14,527180040,20,RL,85.0,10176,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,2,2010,WD,Normal,171500
14,15,527182190,120,RL,NaN,6820,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,212000
15,16,527216070,60,RL,47.0,53504,Pave,NaN,IR2,HLS,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,538000
16,17,527225035,50,RL,152.0,12134,Pave,NaN,IR1,Bnk,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,164000
17,18,527258010,20,RL,88.0,11394,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,New,Partial,394432
18,19,527276150,20,RL,140.0,19138,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,141000
19,20,527302110,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000

Program to replace NaN value in Lot Frontage column by their mean value.

In [4]:
df.fillna(df['Lot Frontage'].mean(),inplace=True)

Program to print first 20 rows after replacing NaN values in Lot Frontage by Mean.

In [5]:
df.head(20)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.00000,31770,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.00000,11622,Pave,69.22459,Reg,Lvl,...,0,69.22459,MnPrv,69.22459,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.00000,14267,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.00000,11160,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.00000,13830,Pave,69.22459,IR1,Lvl,...,0,69.22459,MnPrv,69.22459,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.00000,9978,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.00000,4920,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.00000,5005,Pave,69.22459,IR1,HLS,...,0,69.22459,69.22459,69.22459,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.00000,5389,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.00000,7500,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,189000
10,11,527163010,60,RL,75.00000,10000,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2010,WD,Normal,175900
11,12,527165230,20,RL,69.22459,7980,Pave,69.22459,IR1,Lvl,...,0,69.22459,GdPrv,Shed,500,3,2010,WD,Normal,185000
12,13,527166040,60,RL,63.00000,8402,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,5,2010,WD,Normal,180400
13,14,527180040,20,RL,85.00000,10176,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,2,2010,WD,Normal,171500
14,15,527182190,120,RL,69.22459,6820,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,212000
15,16,527216070,60,RL,47.00000,53504,Pave,69.22459,IR2,HLS,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,538000
16,17,527225035,50,RL,152.00000,12134,Pave,69.22459,IR1,Bnk,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,164000
17,18,527258010,20,RL,88.00000,11394,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,New,Partial,394432
18,19,527276150,20,RL,140.00000,19138,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,141000
19,20,527302110,20,RL,85.00000,13175,Pave,69.22459,Reg,Lvl,...,0,69.22459,MnPrv,69.22459,0,2,2010,WD,Normal,210000

Program to find 25th and 75th percentile .

In [6]:
Q1 = df['Lot Frontage'].quantile(0.25)
Q3 = df['Lot Frontage'].quantile(0.75)
print(Q1,Q3)

60.0 78.0

Program to find IQR value.

In [7]:
IQR = Q3-Q1
IQR

np.float64(18.0)

Program to find lower limit and upper limit values.

In [9]:
lower_limit = Q1-1.5*IQR
upper_limit = Q3+1.5*IQR
lower_limit,upper_limit

(np.float64(33.0), np.float64(105.0))

Program to find rows which has value lesser than lower_limit and greater than upper_limit.

In [10]:
df[(df['Lot Frontage']<lower_limit) | (df['Lot Frontage']>upper_limit)]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,5,2010,WD,Normal,215000
16,17,527225035,50,RL,152.0,12134,Pave,69.22459,IR1,Bnk,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,164000
18,19,527276150,20,RL,140.0,19138,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,141000
28,29,527427230,120,RH,26.0,5858,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,184000
29,30,527451180,160,RM,21.0,1680,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,2,2010,COD,Normal,96000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2917,2918,923228180,160,RM,21.0,1533,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,12,2006,WD,Abnorml,87550
2918,2919,923228210,160,RM,21.0,1526,Pave,69.22459,Reg,Lvl,...,0,69.22459,GdPrv,69.22459,0,6,2006,WD,Normal,79500
2919,2920,923228260,160,RM,21.0,1936,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2006,WD,Normal,90500
2920,2921,923228310,160,RM,21.0,1894,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2006,WD,Abnorml,71000
2924,2925,923251180,20,RL,160.0,20000,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,9,2006,WD,Abnorml,131000

Program to find rows after removing rows which has outliers.

In [9]:
df_new = df[(df['Lot Frontage']>lower_limit) & (df['Lot Frontage']<upper_limit)]
df_new.head(20)

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1,2,526350040,20,RH,80.00000,11622,Pave,69.22459,Reg,Lvl,...,0,69.22459,MnPrv,69.22459,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.00000,14267,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.00000,11160,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.00000,13830,Pave,69.22459,IR1,Lvl,...,0,69.22459,MnPrv,69.22459,0,3,2010,WD,Normal,189900
5,6,527105030,60,RL,78.00000,9978,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,195500
6,7,527127150,120,RL,41.00000,4920,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2010,WD,Normal,213500
7,8,527145080,120,RL,43.00000,5005,Pave,69.22459,IR1,HLS,...,0,69.22459,69.22459,69.22459,0,1,2010,WD,Normal,191500
8,9,527146030,120,RL,39.00000,5389,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,3,2010,WD,Normal,236500
9,10,527162130,60,RL,60.00000,7500,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,189000
10,11,527163010,60,RL,75.00000,10000,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,4,2010,WD,Normal,175900
11,12,527165230,20,RL,69.22459,7980,Pave,69.22459,IR1,Lvl,...,0,69.22459,GdPrv,Shed,500,3,2010,WD,Normal,185000
12,13,527166040,60,RL,63.00000,8402,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,5,2010,WD,Normal,180400
13,14,527180040,20,RL,85.00000,10176,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,2,2010,WD,Normal,171500
14,15,527182190,120,RL,69.22459,6820,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,212000
15,16,527216070,60,RL,47.00000,53504,Pave,69.22459,IR2,HLS,...,0,69.22459,69.22459,69.22459,0,6,2010,WD,Normal,538000
17,18,527258010,20,RL,88.00000,11394,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,6,2010,New,Partial,394432
19,20,527302110,20,RL,85.00000,13175,Pave,69.22459,Reg,Lvl,...,0,69.22459,MnPrv,69.22459,0,2,2010,WD,Normal,210000
21,22,527358200,85,RL,85.00000,10625,Pave,69.22459,Reg,Lvl,...,0,69.22459,MnPrv,69.22459,0,1,2010,WD,Family,170000
22,23,527368020,60,FV,69.22459,7500,Pave,69.22459,Reg,Lvl,...,0,69.22459,69.22459,69.22459,0,1,2010,WD,Normal,216000
23,24,527402200,20,RL,69.22459,11241,Pave,69.22459,IR1,Lvl,...,0,69.22459,69.22459,Shed,700,3,2010,WD,Normal,149000

Program to check if still their exists null value.

In [10]:
print(df_new.isnull().sum())

Order             0
PID               0
MS SubClass       0
MS Zoning         0
Lot Frontage      0
                 ..
Mo Sold           0
Yr Sold           0
Sale Type         0
Sale Condition    0
SalePrice         0
Length: 82, dtype: int64

Program to check if still their exists values lesser than lower_limit and greater than upper_limit.

In [11]:
any_outline = df_new[(df_new['Lot Frontage']<lower_limit) | (df_new['Lot Frontage']>upper_limit)]
any_outline

Empty DataFrame
Columns: [Order, PID, MS SubClass, MS Zoning, Lot Frontage, Lot Area, Street, Alley, Lot Shape, Land Contour, Utilities, Lot Config, Land Slope, Neighborhood, Condition 1, Condition 2, Bldg Type, House Style, Overall Qual, Overall Cond, Year Built, Year Remod/Add, Roof Style, Roof Matl, Exterior 1st, Exterior 2nd, Mas Vnr Type, Mas Vnr Area, Exter Qual, Exter Cond, Foundation, Bsmt Qual, Bsmt Cond, Bsmt Exposure, BsmtFin Type 1, BsmtFin SF 1, BsmtFin Type 2, BsmtFin SF 2, Bsmt Unf SF, Total Bsmt SF, Heating, Heating QC, Central Air, Electrical, 1st Flr SF, 2nd Flr SF, Low Qual Fin SF, Gr Liv Area, Bsmt Full Bath, Bsmt Half Bath, Full Bath, Half Bath, Bedroom AbvGr, Kitchen AbvGr, Kitchen Qual, TotRms AbvGrd, Functional, Fireplaces, Fireplace Qu, Garage Type, Garage Yr Blt, Garage Finish, Garage Cars, Garage Area, Garage Qual, Garage Cond, Paved Drive, Wood Deck SF, Open Porch SF, Enclosed Porch, 3Ssn Porch, Screen Porch, Pool Area, Pool QC, Fence, Misc Feature, Misc Val, Mo Sold, Yr Sold, Sale Type, Sale Condition, SalePrice]
Index: []

[0 rows x 82 columns]

Program to find shape of old and new csv file.

In [12]:
print("Original shape:", df.shape)
print("New shape after removing outliers:", df_new.shape)

Original shape: (2930, 82)
New shape after removing outliers: (2654, 82)

Program to create new csv file.

In [13]:

df_new.to_csv('AmesHousing_cleaned2.csv')